#!/usr/bin/env python3
import base64
import json
import os
import sys
import time
import urllib.error
import urllib.request

_SMOKE_STT_SAMPLE_WAV_B64 = """
UklGRopSAABXQVZFSlVOSxwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAZm10IBAAAAABAAEAgD4AAAB9AAACABAARkxMUqgPAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABkYXRhkkIAACMAcgCBAGMAMAD0/8r/rv/D//3/WQCIAIgAYwAPAKj/Yf9k/6//BgBTAJoAlgBTAA8Aw/+f/7f/yv8pAG4AagBjADoA/P/p////AQASAB8AQQBUADwADgDx/9X/7////+r/8v////z/+//q/+L/+f/p/9j/+P/c/wUAJAACAPz/8f/S/xIAOgBBAEMAGgDw/9H/zv/E/9r//P/w/yAAOQAtABQAwP/B/+j/0v8SADcAKABfACwA1/+//57/qP/o/40AAQEMAboARAAEAOr+ev6T/tP+wv98ANsA1ABkAK3/FP/q/hX/u/8nAGMAmgCFAJEAzAA/AKv/h/+t/1b/rf/S/9L/bgBeAEQASQAyAAIAlv94/3P/5P+KABwBAgE2ADX/FP8u/5T/NAADASoB7gDfAJQAqP9E/wX/cP9wAOYAAQH5AGMAk/8l/07/DQBmAC8AgAASAc8AegAlAOn/a//0/mf/dwB5AYsBFQF/AMr/f/9D/1n/1f9cAPkAUAH/ACkAaf8p/9X+pP5u/1YAbQGdAesAogAyAJH/X/8g//T+tP+8AE8BvQAJAMf/VP87/4f/y/+lAHsBMAEJABH/HP/B/xYA7f/5/2oAkQAhAKf/xP99AGUAuP9I/3////9NAE0ALgBxAOIAzP91/3L/Qv+f/2kAAgGLAEkAkwC6/3v+DP/5/7cAZgFJAb0A8f/7/1UAj/64/un/YP8O/yj/awB7Ac0B9AEiAYj/W/6M/pr/mQDXAT0CiQBS/+f/Vf+5/qH+V/94Ae0CsAIjArL/GfwI/L/9M/+uAKsBwwLuAcoAYAAE/8P9tf4i/6T/iwFSAWcARwDQ/q7+t/++/w0A2gALAbUBNgG0AOT/gv3d/dP+pf/NAM0BUQJOAt8BRQDG/oz9RP1a/pT/mQFZAj8BhgDh/4L/wP9Z/rv+9QAcAbwBmgHQAM7/Kf7B/Sr+KACoAfMAcwGuArYBOQD5AG4A6P1E/QT+7P/tACkBeAHcAD4BwQD3/xQAagBCAEgA9P5y/rj/PwHUAesBPwGq/0EAWv/n/Bz9cv8iAlYCWAAEAHD/Jv79/2n/7v41AowBYwH7//7+GgD4/yX/8v7CADEBwf9eAK4AX//V/qwA4wHG/6v/ZQFBAMD+5v5/AAQAO/+RAcgAHv91/y//lQDiAAsB/gHCAC8B+ACL/f79J/+7AFQD8gB+AbMC+wFRAOX/uQBb/zL99v29/xb/cgBvAnf/kf/nAacAFwFdAaT/Z/7B/8b/1gDk/03/XgCa/h7+vv4S/88ADAIaAv8AI/+T/rj/2v6J/tT+nfzh/hgCpQF5Ap8CogDM/5f+DgBKAc7/ewLzBM3/1vxH/Nf7Nv5KAqkEOAOvA6gCngDB/1T+0ACYAEYAIgJ1AFz/KgA6AJX/swHJANgAfADC/QD++v1OAHgB5/7lAM0Adv/z/3b/zf3M/mYATQAxAAUBwAEIAEP/jAA8/jcASQJ6AJQACgCS/2kAiwEzApcBKQAMAAcA1v2//usAOQGSAdcAmAIAAuX/gQCE/zL/N//c/qP+Wv6z/yz/qwD9Ad0BBgIzANH+Yv5K/p//1QCqANv/pwHGAJb+k/7y/i4AoQK2A4QDnwB0+2X8gP4y/6X/CQE/BGEDqgBY/7b+Y/6//Zn87/4XAYwBpQLwAgADgwHx/7T/TP8C/cT7iPxi/nAD2ASqA+gCrAD2/Mr76/4RAPcATATuBOADOAGI/vr7qPuS/l8BuQI+A7ADOQJk/4389/kW/b4BRQIvAywCIP7U+5z/mQA7/p7+aP+d/zQAAwAmASwAZ/+9AEIAVf5T/5YAgP8oAtcCaAEGAKj8gf2v/cQAzATeAj8ECgWZADn86/t//R/+JgG1AtYBwQD9AGYAIvyV+1H+kQBVAqUCKgK8AF8CyAMSASMA/QAi/+v7l/sX/bL7Jf5/AmAGcAqTB8EAlf36+6T45vjO+4L9TgA9A4AE6gSiApH+B/xe/iYBV/8S/uX9Sv7B/dX8p/8gAjwD/wSvA1IDdgHg/Pn6aPuh/WEAsgH0AkACbwF1AnECIv7b/ZcBiwKXAZ0BxAB5/mL+ofuN+Lv7VABsBnAHowQ7BEUBdf+S/Kz4aPkU/EoBtQIaAEn+xgDaAoYA0/7AAbsEWQO0/8b8DPoF+jT+swAQ/4n/NQI2A0wCeAAA//f9MP9rAIn/HQC6AjQFNAFF/zn+Of5F//T8sgCqBJwDmQOBACj7svhf+gP8xv85BTIIuAkYCeMFEgHC+Z/4ffqD93L3Yvw3AWoFiQQcAm8CuQF8AKL/i/x1+gv8Kf06/Xr+o/9aAiAEOAJvAIYAaQA/ANP/0v6u/SwAhwENADQAzf7I/TIBDgfvCNkCtQCEAhAAnvmF98j5l/wwAW0IQwtHCj0IkgR6ABX7sPeU+Hr68f6GAC0BkgOBAsX+5fpd+/L/mgNtBjIFAADm/Yb9ofgM9CHy5PYB/wIFagryCpgGBQI7/Yz4v/NL9Kz6q/9r//UBBwdFBpMBNv1i/nkBIgSJBc4CQQGGADj99frY+4cAxQFJA3AFxgTyA7oEkwX5BOj/qfuE+pf6P/yH/gwAlgIbA3UAU//h/gT9KP3b/e/+Bv+j+2X5DvqK+pD6rfwU/jgBzwRsBKYAEfuD+OP4wPbO96z9KgKKAu8CpQRzBasENQPnAzUDogDCAH0CYQLXAZAEgAXyAgYD+wbKBnUFrwcPBiYEVwMRAcL+U/z3/G8AIAKJAzMEBgOnAt8BWP79+LP1NPR486rzb/Ro+WT9ZPuf+yn7hvhz9DnyBvVT9a32VPuS/uD99fwuBHMOyBHGDP4F/AHvAHD9OveR/FYGXw3hEfERTg6cCxYKWgvrCRwK4w62DloKQgAW+H7zePRW/cIDYAY+DRYTfgk4/h32pu8A8qHwsuiR5JblkOXX5O/gndoK3Prj+fJlBicUpBeCFk8UNggT/Ej28vTN+C8DBRFNFPQPYQ0mC5sGIwfqDHIREBbyFzkSAAhIAfH+2f8MBIMMlBQYFdgQaAsGA9T4M/I17iPthPDe+5UGhgIC9lDwGenn2GLJ07yVtrfCENxj8S0HXyEHNhA6zyxfGf0Dfu5w6Ajp3Opi9s0HthBAEnoQ1RAhE5sWhxiXGqMXMhNpDDEAMvfm9QT9DQh6Eboa3x11GCwNe/849JbvsfBb9c74e/r8+7f52e4u4wXZ6cwKvuWyqbcDy9jocgatIYw2g0F+PPUmQwcw73LjQ+LK6LH1l/9+CU4TbBb4E0sRVhP4F9sakxoOE6gHSP4A+pX3o/c4AIUP/xytI2IhiBe6B9L5KO996F7oNe569x//IgFd+cXra9pmyU+3uqgftKnMP+snCJ0kYztQQf8/5ix6EJn0heWm4xXll+0p97kIgBbUF24TTw4sEaEVPBjYE3oPPg0ZCOQBU/ky92r/jA4GGjsf3SBNHVcSxgB476rkdeEc6E/yj/v0/x//lffx5UbNZLdXqw2sG8Ef5c0KyC3iR0FQnUWbLscOKPRp4c3a8uRo8A36owYqDtMM7Q0dDy8SWRn7HjMg1BpmD5cE/vkd8hr1s/92Cd4WOiIaJRYfXRL7AZ7yyud+5UrnXOoN8gX48/d/84fo/9N3vSWvwrRfx+Xg+QWiLQZJRE/cRSAtew8Q9i7l2dxj3h7uEf6+BWwJsgyjDCgN4RQMHNEfZSKqIN4VhQQ19i7uI+8l91YEURMsH7cmSSJJFMgCofTm6vzl8ubl6bXurPPE8xTr1NokywO6gbJqwZbbUvjOG6A8Bk08SbM4bhxyAK3nB93n36fpg/QIASwMKg93DMINSBCWFdcb8iCpHSsVvApA/hXzjPBl+DsD+g0rG00kTiITFn0FIPhD7qXp2uhY6i7uFvMc9PDscN/IzhW9n7EduqfP4e62EJsyq0iSTWFBliSmBsvtUOCj3svkQPHR/AYG7gpDDhgQkRIhGXMgXyf1JawcGQ7A/Yfx++vY71j5lAiNGb0kcSayH2EQe/+09C3tS+cI5M3mQetd7tbrV+M31i7F6bmnu9PLMeXkBmwun0ciT1FEpS4bER31JeDS1XzZ6edL+XcEYQlkEcYWWhokGwkfnCH5ILAbng0P/+/zIPLF9O75XQcxF5ojxCTiHS4QCACw9Ajs9OSc39bjMexV7rTr3OXX2GnFDLcNutnLPuyDDqIwaEfsT1ZJ2i1NCUrphtkX1wDfM+s5+eAK3xSfF7YUHBMrGR4fASBVHVQZlg8xA+v52fJj8Jr3wAa0FqYfvSKGH+gSzAJX9Evoidxv2LneQubZ6iHop+G31TnF8buCxIvZpPb4GwdAV08hTuA/cCEI/kviUtTx0LzdAe/X/JAKpBXkG8wbEhxJHy0hnCAWHCsTowUv+7rzb+4m8kL+RA1wGzAlpSS4G1sPiv6n7oDg39W815rebeEh40ziM9yI0QLHGcd61VHv9w3ZLuhEbEpKQtUqjwjH62Hbk9RX2Gjlm/bDCcYVphuoHTgeniC8Hz4c/hdlEi4H4Ppw81PxVPRy/WgLmBn8I7Am7R9BE9cCXvHi4GfXu9Uf2mbhweXc5OffF9Q5ywXLKdM/57QB8yE7PXFJc0QgMQEV8PWT4efVxdQB4JnyMANBEN4ZHh6CH+wghR9sHGoZ0RNWCr79i/Ww8hT0gfvbCFgX6yClJBAgIRNTBd71k+ZH2gjYtdw14fTlZObj4TXURcsJzQvTBOLt/PEdDjfSReVEzzFxGOT9yOcz2C3WDeEm7+4BTBHOG/MeeyDQIUIeyhuOGJsSigjp/Uj2M/GX8h/6awcJF5wivyZuIn4Xrwis9uPkPNhx1m/aSN+W433j9N711trOS8xU1Wzp5wPxICk7gURSPrws9BTl92rhHNiD2I7jDvSxBdASVBx6Iukj8iLfHiwavBTHDFUDUPjP8envB/RY/oQMEhrgIz4opiJ3FPsELPJQ4GvWs9TE2E/e2uN35HPfOte30mrVedsa7E0IsSMKN04/iTntJwIQRPfH4prY79w56fb3KgYtFLgcrR+mISIgwBzRGEUT0gqnAYH5A/IE7x70zgBUDwkcZCXgJh0gLRTcAiLxAOGn1WvVotj83sDj9uQP4PbXcdU02eXgBPDrCWAjgjVvQQU8JSgjDir2B+KS1o3ab+ZC97YJIhhoIBUjCCRoICcbdRb/D+QHyv+6+PTxxfA09+8ClREMH1gm9yZOIJwRPP0z5g/VTM6Jz27VTN1n5Drn1eMV3O3a29nb4rf1BxDWKI84CT3bM+0htArj8MHevtbw3NbqyPv0DEgajCRHJ5AkgSCpGhMVCQ0oBVz8APW08WnyePl0BnkV2SGvKGQnjBxJCrHzz902zsTHTsyy1cvcGePM5ETg9N5n4bzmXfTeC8YjLTW4PEI1eySHDPrzn+DU1e3YqeaB+UgN4h3JJ6UsoCqVI4cb4xMYDMAC6vl38h3v5fAO+OMC4w8lHmwn3SdaHxUPmvkp5HzTucg9yXTQY9i53vTgr+Oq5ablMOkc9jEJxR0RLns4xjXqKV4X8P6/5ynaQtld4ErvDQTcFqEk1iv1LCgmdx3NFFULPwGg+ez04vFP89L5XwOADjsZYyEvI5od6xBx/TjoxtjazQPJUcw11lTemOJ55mfnAemB7Zn04AHME5ImbS8GMlct2RzaCE7zueOM2q3eAuyk+mwOFR/qKf8skisRJZIZ+w90BWT8TfVE8TnylPZs/zoJBRSTHdwgFB28EEMAPe9r3pnRrMlcyqPQ79U81yfclOXX6WDxIv1pDLkcXStvMk4uTCZmGTkFjvLE5Cjf++FU7a388ArIGlonCitcKqgljB26Eg0Ho/ww80PvyfCE9XD+Ogh8E+8bTh7JGXANLf7c7h3f1dGFyvvJrcw5zl3Q8dhO4VzrafcgCf4YGCeKMpY0/C2QInAUhP+5693hsN0C4oTuWP54Dh8fES0rMIku1ifJHH0PaQFv9r/u+eyU8ID3hgG7DZIXDx0PHvkVmQcQ+MDnSdc3y6LIeMiSyN/IX9KJ3O7mp/a1BsQXOSdnNDc4/zB1Ju4VDAO775bjNN6Z3z/rNvp7CgEbtChvMEswtytOIUAUcge9+q/wD+yr7U7yu/qPBcQPxxdEGvMWnwxu/7zwqeCO1HnMHcl2x0rGFcu41IreaezJ/VURsSInMTU43jgNMmQjwxDb/KnswOIB37Djb+7L/jEQUR+BKv4uKS6PJyAd7xDyAuP46PGn7o7wTfaI/38IFhL7FlgWzhACBwP65OqV3ZzTOc6dyynIScUezOzVDOH471oEqReSKeU3ND29OdMvth8LCrvzWOW93afccuMr8VECVhTcIvgpRixZKZIiPBddCsr/OveV84byifW7+zECvAn9DlMR6A4/ChsCjvZb6xLiEtoW0n/MN8a3xdLLe9Ix4fDxQQhpHJktVzkGO4Q2EirEFzUD2/FC5xbioeT+7YX6VwhaFsgfHCQIJQMhzxk2Ee0IBgEZ+3z4WvgD++D+bARGCp4NSA4PDBgH5v4c9ZPrauJA2q3T5czAxSzHkMw51Ezi4fTiCjIdkC6MN0A3UTNRJ5AV+AKu82Dq++VD6XrxF/12Ck8WlR5mIaghbh6QFuQNUgZuAAH8y/p++3j+1gItB24KdQsGC3wHyQIg/P3zaO1E58TgNthmz83IwMfExzzPWdsm7uwDyxcFKlM1xDnZNNgoABkUBpT3l+x56AXrfvP8/6ULjBapHmMhih8BGxgUQAs+BOz+m/yS/Oz9YwGTBOAHwAkGCgkJnAXKAdj8F/e+8Qvsa+Xt3OnSiskfxmvFr8oe15PoZP6xEmclvTBxNSMzrigCGwwLkf5y9arwsfMO+uECJwxYFOYabxuuGVsVyg+ICVMDSQBu/if/VgCgApgFxAfcCXQJ+wexBecBrPw99zPyJ+zh5CHdG9TXybfHvMZNzDvUHuUT+hcMJyBzKtYxKDHaKWAeyg6SA2n6sPU29jb8gwX5DWYWHxvqHLIawhQKDZEEJf+S+jX4SPkA/SYCbQYdC+oN/Q34C9QHdAJO+8L1EvHp6n7lrd/S19/PWc5czJDPQdVx41D0ywOmFIYhrykcK10mRx/UEhsJBAFq/ev9xgGWCWARnRjUHJAc3hlDE2sLlAFb+jH1zfPH9dj4Nv8EBbAKzA3NDq8NCwm4BPH90/dA8nXtveiZ4jTd99XL03bRbdRg2WjiNe8b/aYKShbrHcEhdSCVG8oU1A0PCfkFUQV0CGENUhMpGB8b3RvPGE8TcwtNA6j7vvUE80jzoPby+jIBQwfpC1YOwQ2TC3kGKgFi+6f1T/Hb7EroUeIA21PYWdV91CLXhd1W53by6v4/C2AUVhorHF8aoxXxELIMhwlWCdkLgxBPFoIbGx/pH7sdVhgEEFAGK/2k9SPwW+6973/zOfn//zsGmAo8DeoM9wl4BVsAcvqb9E3wnuvf55PgZ93R28HYVNuT3FjkKOvH9TP/PgZtDf0QORNHEQgQOA/bDZAPcBH8FBEZ4xxJH9ceHR3RGGMSJgpyAhT7CPWh8YPwHfF78174iPyeAEwEHwbBBi0GOAR2Afb9PPrF9qLyE+3g5ufj5N6a3X3cxN4d5DHqXPIT+RkA1QXjCHkKFgpkC+MLzA31EL0UxRrCH0gjTCVlJGUhnBvGE5AL0QIe++H0c/GD793vxfKw9W35ifx9/6gBhgJHA90CFgJJANv+Tv1w+gP3KfJK7hLq9eVh5NLj5OOu5kXqFu/38tr35fuQ/r0BUQQcByEKGg8fFOoYMB4PI4wmMyh7JxQlth+hGPUQygcc/8T34vE47oLsRu3h73PzbPe3+mv+xf+oAAcBb/81/5397PuK+zj62fer9Zrz1++l7cDqtukh6a3omupu7IXvZPN59qD6Xf5YA44HggyREVEWqRvZHxUk2iUMJ5Mm7SNLHwkZBBGTCBsArvin8r3uPO3b7T3vzfGy9Zz43vvJ/fr+r/+k/9b+oP2A/A/8Ivq799b1IPSu8trvwO6i7NPrH+uc6iXrnes87nLwtvOL+Pz9FwQtCgsRwxe3HSAjuSZmKEkpFSh/Jc8gxRrzE/YLlgSo/V/4GvSS8fjwB/GU8jf03/W59wz5PPrH+h77rPsK/CD8P/z9/HP8+Po9+WD3iPSF8WjulOsL6tvoAOlh6Ubr4O2h8Fb0NvgK/cMC2wgOD0EVDRyUIY0mLSpFK8YqfSgkJModJRbNDckFJ/5O+D30UfLk8R/yRPPp83f1nvYI96z4Jfkr+1v7t/qf+6z7Wvxt/DX8R/wW+1z6E/gS9bXydu/i7LDpyufS5l7nBema637wbPU9/PICBArcEEEXGR3mIXcljCeQKCAowiXcISEdshZZEIEJxAJJ/cP5WvaV9IP0s/QZ9Rj1nvXf9ez1rvb+9w740vhW+qL6K/x3/Rz+hf5R/fD73Pma9g7zW+9B7Grp4OaV5aXl0+bg6EnsMvBz9eL7SAI3CYoQmRcEHnEjVCfHKeYqLiqTJ7cjah6+F7kQ9whfAqr8s/g99vb0LPVI9fH1r/WG9UT2e/Ub9uT2FfgA+uT7C/63/1QBxAIMA6oBVP+D/BD5a/XA8Hrs6Oj95AHjp+GK4cLi8+Qf6YPt4/L++N//6gYoDlsVpRw5I6sorSw8L6EvRS7vKt4lkB8LGGcQbAgTAQz7+fXd8mDxlPAf8XDxuvLl85v0iPX19mr4JvqM+1b9Z/8VAfgCSgP6A3YD5AGh/nX6Ifae8ebrkefb41rgSd+m3rjf2OET5pjqPu8/9Z37mAJ/CTYQWBeOHooliStMMLYzWjUMNPgwWCv6I7Qb4xE5CKX/ufhi86bv3uwB7IrsJ+0Y7sXuePAc8nX05Pb++Lf85P/JAiYFugaECFEIiQcVBpMCp/6C+cH0JO/46Y7lTOHB3snc7tt73czfPeOb5+/s0/JT+cgACAgSD1IWvB2gJFMqky+HM4o1aDVWM2gvjylnIucZZxAoB8z+oPY+8ELrmegQ6P/nyejG6tjsdu9q8ij1S/gM+03+vgFFBK0GzwhyCg0L1AmBCKAFsgEX/fP2SvET7J3m5uJA3wvdzdtX3M3d8N+r49HoGu5B88X5PwANB8YOFhZnHR8lgyyfMsg2SjkFOm04PjQILikm5ByjEskIWf/d9ljwEOxr6bXoLumt6avqeuu27HbuD/C/8gj21fm0/sgCkAeTC/cNiRBVEE4O5wuXBqwB4vp083rtS+dm4nfe49tU21DbZdxy3orgieNR50zr+++U9E36aAHuCI4R5RqCI8krfzN0OhI/2EDnP2k8/TUzLW8jZBi8DbIE4vsO9dnvaezL6nbpG+lV6b/oAenW6SHrc+2v8Lv0mfms/m0EZgnvDEQQmBFUEIcOXgoLBSP/Bvjs8Brr9ORS4A7d19rG2RHaMNvI3HLff+Iw5r7qTu8b9c/7kwLmCsITXRx4JUYuKTb8O1xAJkIGQUQ9mTZXLr8kGxqxD2MFYvwM9fDvi+wL6qPoKehW6Djo8ue76EzqFuzV7vby1/dm/RIE4AoREIwTchVSFY8SXg7mCJoBaPk38YfpyuIi3RjZL9dI1dXVDNiH2QTcV9+f4i7mQ+o88Cv2pvx9BawP5Ri6I8AuXTi3P2pFj0gqSHZEwD7BNjcs7yBfFmALYgHX+crzNe9w7HPqy+ii53bmZeUz5SLlPOYK6S3t0vJ8+TEBygh9EMUVLxnjGtMZTBd3EhAM5gSr+5byReor4iLcqdaR00HR3c/60EvS1tSI12Xbm9+75EPq1fDc+K8BMAvNFVchlSuwNSQ+A0Q3SNtJWEjpQ4w86jOOKXgeaxNSCSAASvgb8nnthunB5qvlk+Tw4rni4OPG5SPowetr8X/3av4FBiANaxJjGP0bAR0nHMIZ3BaiEH4JQALC+anwI+cf3jfWONCZyszG6MbDx7jJMs/31Ajb+OFN6m7xqPiyAJ4IcxAYGRUiYyrDM9M8CEQWSCFK/kkaRrA/jDZjKwIfoBJbBpX76vGf6o3mfeNO4u7iuuN85SLnkuh56gbtgfAy9Ln42/6fBZIMWRMTGSwdACC1H6cdXhm3E00NLgXX/F3zXetD4uTXkdD2yuPFp8Fewf/DxceVzKfULd6o5V/uR/cD//gFYQ3rFDMc9iO2LFA0LDoVQZpG9khWRzBEjj4KNWcpKx1EEPcDM/kZ8A3pDuQa4u7hZOFB4jvkHOYQ6Bvr4O6+8gr31P1oBK0KsBE0GCgckR5eIHYerxtGF3cStwzkBVb/xPjZ8Anpl+C510bOb8YZwKq6xbetuNa+2sVOz2Pbx+iN9CEA2gmtEQwX3xsmIFAjgSbMK88x3jaaO6BAHUNYQ15APTn3LyAk9xaPCG/6cO6D5P/ekdu12oTc8uAa5aLp2+3N8Yr1DPhU+7f/rgRdCmIQwRbNGyAgACKZIQUe3hjxEs4KVAPg/MX2/+/46TXkFN7l1XnNb8WBvTO4ZLXWtgq8JcZH06Tfxu4L/qcLoxQcGzQfzCGuIt8iuCQfJzEsTjLPNww8zz5rPyI9JjanK6If9hF0A3D2Puuj40Xflt0/3iXhHubI6p7uDPMw9+b6mv7oAmIHrgzGETkXAhuVHUUfjh6iG5sWfhDoCVIDevzs9jDyFO5t6w7nV+F62i/T1sgbwC+7Grg2uKG9RsiH1Wbk2vWWBQsRBRnRHrYgzx4vHB4bDRrnGrcf9iaYLQU0BDvhPSE7ojR+K6Iepw93AQn1Peuw5Fjij+Jh5YLpCu9/8j71R/hg+s37EP0jAOsDZgh/DTITyBfyGuAcgxzQGXMVcRAtCtADw/3V+IP0wvCL7kzrlOdm4pTdrNiS0VXIccT/w+zBsMMazJ/YFeSQ8uD/dQvdE4EZ2xs/Gn8XzxXOFdYUEBcYHZ0kuyvGMSo2eDenNA0u+iNeF48KmP+q9Y/tIOq06VLrxu1W8ZT0TPf2+JD5//l0+n38Q/+cA8kHLQ53FN8YEhxIHRgcWxheExcNcgbRAKP8kfmk9o30o/PR8RvtPegF4nPbg9GSyZXCkL9Zvj/C3slY043hIO/K/c8H2hGOFzQbsBliFzoVhRRFFSoYZB33I8wrvDJ2Ns82FDNwLE8i+xVMCGr9R/R57f/pwelx67XuY/JF9Xv32vhf+gz73ftq/YwBKgfRDKwTkxmOHtQgwSA/HaEXDhExCRcCfvtW93T1xvTu9Dv1hfTs8Zzt0uZ73lzWU89FyEjC9sEIxa3J2tC03FzqGPa/Ac4LFBMlFvYXTReqFCsSmxLIFMwWgxu/IgUqOy5vMe8xbC2MJbYb3BCdAzv5KPJD7Z/qbOt17vHxxfX7+Ff7qvwG/c7+SQAWAlAG5gxFEhoYSB7rIRsilh+6Gq8TJgvIAvb7VvZt88HzRPWo9lL4F/na9hvy7uqn4ZfYBM+0xjXBXsCJwvTIm9Gs3RfrzPe6AVgLtxFmFIMTgBISEKQOVg5UEBoU8BlRIVwo6S3CL6QvHSx6JIMaRA8pBCz6mvLQ7EbrXeyG77fzHPeK+kX+vQBOAb8CfQQNBr0Jjw0sEaMVvBshHoIeihwXGSITMAtoA2n8+fZT80HzffRf9hr5Afyb/I/5R/RY7dLk2tjXzXPFQMHmvWTBDspr1BDgfu4F/VEGKw1nEFoSvw/sC+8INwlfCkgOKRaFHmAmCS6DM9QyNy5KJ/YcuA98AqT3HfDi6y7q/exZ8Y32AvzrAc4DIgREBM8EcAOsAzYGcQrWD9cVIBsSIMwh/SDuHYgXOw+iBiX+sPWx8OnumO+x8aT2Yvu3/oD/Wv0V+RnyeuhS3vDTl8sRxZnB4cBjxgfP7deL4/7xVv7OBfkLABD0EZAPhA0tDN8NPQ+GFKQbWiPEKQcwQTJ0MDQqISH8FaQIlfth8K7p7OVJ5pjp7O/59sj+qgRtCH0K9Qq3C4kLGQuaC1IPRRQeGZUcxR8YIT0fihqVEhMJVv+J9mbvMOsp6rXsp/HQ9wz9sgAZAo4AI/xQ9BDq7d8M15zNscTGv3nBssazzcnVsOK98qH/GQhADmET7hPwEt4PFg7QDTURFRaeHVEkkyt5MSYzEy/pJ3IdiRA6AaTz+ehN4mzfpuEx57rv1/mHA9YK/g8pE+wTthKsEFEPvQ7zDzkTEhc5Gt0crh7ZHMwXOhCWB5r9YvMm6//m3eUU6Obtd/VA/WkErQgLCAYEP/0B86jmEdmQzv3DZb1vu4q+u8UW0Fzd3esK/FEHyQ4rEgIVXBMGERcPkQ+oEcMXLx+eJp8tQDPfNLIxSilfHYAP1v+t7wXktNtP1x7ZnuBs6XL0cABJC0wTChguGmoafBgXFkEVAxUUFTMXsRqRHNkcuRvYF9MQbwfV/IXyD+li4qbg/OI+6LrwdvraA0gL2Q7RDRAJSwG89X7nHtrozsHCGLgWt7G8BMRIzKvaoOyt+7MFWw6NFKAUPRMSE4ASVBEBFaYb4yOqKmswMjXrNiUxxCbXGacKz/n96XHdwNW90//XHuBs6on2NgToDp0V3xmRHJMcmBtCGU8XgBYWF2wYORq7Ggsa8Re1EyQMpwLV+M3v+edn4oXg+uKE6enxBfsJBMcLnRDPESAOyQbw/VP0Aehu2WXM9sLxukC3z7lRwU/Metsj7Wf8SggpEfwXUBouGOAUdBNfE5IVFhqCIEIoUC9bMw40NS9dJT8Ypghe9iflO9jZ0B7P2dK53IfrgvuzCs8YPSJPJ6koSibdH4YZkRN8DykNRgyTDRURMRMxE7URwQ0wB3v+f/Ra60jk1eDl4fDmce+7+sMG3BGvGWkcIRqtE8kIuPmS6RzaM8v3vZmzsq6usey5QcN904vndfkqB4QUDRyfHsUdvxqFF3sVKhUrGSUgLicPLoc0pDbMMswpBhyOCpj32eTP1C3K8cZLyrXTy+P89nAI5BcPJpsulDCMLvko4CDcF94PzwlSBsUE8AUrCaELnQzQDH0KkwSK/C30KOwV5VThzeEp5n/ut/owCIkUph5tJdEl7R+hFEEFWfOU4LnO0r6asuWq5ap2seW7ncq83Vfx6ACkDZ0X+hz+HaYbsBhuF+kXYxpvIKcnuS0JNDg3LTTEK8weSA4K/YPr/dm9zPnG5sdIzi/a7eo2/gYRVCDpKzkzlTQ8MaUqkyH7FroOfAjUA6YBhQK/BAQH9wfQBhIEP//h9/LvROlB5AXif+Qt61X0AADVDfYaliQRKnQquyV7GloKCfhl5MrRssJntx6vBaqxq7i1QMJtz2Df5fIIBZ0SpxvHIZkk0yQBIw0hcB+BIFUjEyfOKUcrMCq5JpMe0xHwAdPxHuM21nTMuMi7zInWyeN29DwHrRkSKTg0vziCNwkyjSlrHioSDQfc/gv6Dvia+ND6Kv4XAUYDlAI///P5XvSg7mrp6OZI6a/v/fixBCkSjh9DKt4v0i8mKuIdeg2b+SDiI80UvjmzZKz0qAOpVLAmvf3Iqdc16gP8oQqxGKUjMSonLcAtPyzzKYEmqiM8I2kiXyBhHiUbXhSuC/wAD/QS53nbJdKGzQ7OTNOM3jHvrwGvFLwmlDSWPR1BJz1zMyknWhgHCf77VvGW6krp7esz8Zz3wv1yA3UHqQa5As79KfiW8k/vjO+h8y77lwUxEsMeTikiMA8yxy0GI9YSh/5L6BfSHcCjtACvYKzKrcayIrxJyGfTsN8z7nr/pA5PG8YlFi82NBw1OjNyLqsnjSE9HMAWvBA/C10H6gMI/W71bO5h503g+dqv1/LYkd6d6Kf2mwfrGVkrKDmYQaVEWUG0NxQqOxlbBpL0Uecn3q3ZydqO4RXrc/UkAG8JeA+gERcQuQu1Bfj+uPoP+v37WAFZCrMUjR5yJpsq9SnUI1YY5Qeh81rdlslmu0WxCKy/rP6xZLq8xJXRsd8W7YL6RApTGXEkcC3WNKM3tDTCLmInsR4rFCwKBAP2/TD59PVn9Qf1oPPN8UbwaO1t6czms+ek6z3y6vynDOwdOC1MOQxC8ET8P2s0ciRSEUb9Oep1297Rmc33zzHYSeSN8mgBQQ/YGRkgZiLwIB4cPxVVDpkISARIAnUCPARvB1ELQg8/Ei8TlhH2DNAD4fbQ5vLVIMeHvIW1YbNKt2S/icn91QDks/AN/esJSRbXH2MmxykJLLYrISetH/8YiRG4CQ4D+P3E+d32GfTr8Q7wI+417HPsVO2w7uPxPPigALQJdxPLHVwn6y0cMW8x+y1dJvcbPBBQA/T1gOk84ALahdUC1dHYxd8N6vD26ASWEwkgmyklMPgx3i0qJmMcWxGXBlr93vav9F72xvr2AFsHJgxlDqYLSANu9xzpMdlJyqG/drl3uMK8bcT8zpjbHOjQ8xn/BwkrEvYaCSJFJtko3ylmKLcjkhxHE6UJXgDn9xvxEe3B6ijrI+317yfyxPSh9zv7af7gAbUG8gxDE8IZhCAEJsIpFiu/KA8j2xo2D/4BRvSI5hbbpdNk0JDRqdeq4XrvF/+NDssc5CmCMj82kDWxMIwnlBu3DuwCtfke80bwbfGA9Wj7TgIjCCcLiAozBmv+MfMs52Hans6Kx1vENMSpxyLOYtSb3Dbl+euM8g/7awbwEWIciSVHLzE1IzUGMFQnrRr0CzL9IfCy5q7hAOE55YrrbPIU+osA+QN9BS8F5wO1AkEDDQYHDF4T/BuJJVgtgTAIL6AoKR3BDTv8a+vR3MXRhsxtzdXTXd4Q7LX78AtPGfEj0SsNMJwv9irJI3sbqBJeCtUCA/3f+BL3bfd7+RD8Z/+5AooFTgbYBNsAo/rL8nbqmuI/293Ue9Iy0tnRbNI11oPaed5D43zpNfCC+YQFbhFnHEUmVy38L80tOiYgHI0Q6APq93jvIeqg6L3q0u+e9QT7S/5oAJ0Axv5U/KH7y/zgAGIH3Q9JGo8kGizSLwUvdyhVHRcP3v+y8IPjqtoC12jXwNsl5KLu3/l4BeAQGhoaIO0iCSQFI/EeAhq7FUcRLQxkB34DSACF/Q/86fsd/MD8ZP4bAFoA9P29+dv0X+9S6Nvgudp11snTQdK40orUz9YE2f3cfOKV6SHyLP2ICUoW+yBmKdMuwS+tKv0icBjnC4b/VvX87XLqQOqS7VTzZflT/ikCiQPPArQA1/6z/b7+JQK/CEgRJhqcIlspIywRKiwjQxh0Crb75O2V4hjbT9iW2lvhbeoN9U0AMwvSE+cZcR0LH1oeHRxcGUkW5BINEAEN5AnNBswDAgFc/9X9FP2r/dn+yP9aAM3/cP1V+brz1O1157rgUtvU1+jVjtRz1KLVbtd62ardA+MT6mXzC/8KDPgWsx93J90scizlJ2Eg7RbkC0kBD/hw8nzvI++O8UX2H/pZ/dD/KQGtAEP/Ev46/t//cANFCaMQQRjYHswiGiTZIaEbFxJcB6H7efB757bhWt9m4MHksutG9Bn+tQdyEGsXkRyLH5ogPB81HM8XAxM0DnsJWgVwAoEAov/y/w4BSgKJA4AEyQQyAxoABvwD93zxb+uW5XPgPtz02LTXYdcg1wnXi9cT2ePbwt/P5bvuVvpsBjsSvR02J4Us8C2TK/ckTBs0EL0Fd/xR9UDxW/Ar8qv1z/mn/cEArgGqAE7/uv3w+zn8Cv8RBKcKDxJpGXofkSJUIgwfThitDrkD7/g77xzny+GP4Gzi8ubG7Zf2Mv/+BrQNMhR2GK0aLBxWHEca3RfGFAcRCw3RCS0HYAWuA+QC+wJUAygDOgP7AnIBnv5S+wr37PHO7OTnF+Oz3pjb8Nj21j7VB9Rb05XT/dXJ2m3hwul/9dwCLQ9uGrwkZyv0LaksbCdZH+0VtQvMApH7c/Yk9Pn09fZJ+XH7H/1h/Tr8W/rW+Hr4Rvnp+9oA5Ac/DwkWLhyeIMshcR/UGroTZwpmAJT3fPBN6+vnkefc6b/s8fD+9l/8xwAVBVEKeA9zE7cWxxq7HcgdPxy3GVgVuw5sCJwDEACN/ez95wC+BL8HUQqWC6oJCgSt/I30fOvW4X/ZUdRe0YLQxNGx0/DWVNoy3Yzg3uS96PLtlvahAEMKuxOKHeQkJinLKTUnWyH5GFwPOQYO/jv3g/P/8s7zm/VN+Mr6TPzJ/ID89/uy+wz80v2qAYsG9wu2EVAXAxtjHIobdxgQEzcM6ASK/YP2ffDO7NnqQ+oS7LLvg/Su+SL/XwS1CZ0NnRDjErAUsBUOFnwVpRQgE/MQtw6jDG8K7gjEB7cGBwaYBdAEuAOmAW7+JvpQ9a3vpumc413eedpH1+nUBdQH1NTUMdY52ffdKOTw6qD0vwA5DO0VUR/oJukqUCpPJoUgtBjgDrMFrv7A+LH0E/R89RL3afj3+Tj7JfvE+Z/46vgG+iH8VQAYBp4MJROhGGEc6h2YHPEYvRPgDIEFdP4/+FXz2u/07d/tJe/s8HrzxfZp+lb+XALgBhEMEBF8FacZ2xsFHAAbkRgZFDcPUgoxBmMD8AH5AUQD0AQ6BuQG3gXGAhD+2PfR8GnpTeJO3LPXltRo09/SHdNz1ETXz9ql30Dlzexz9o0BIwywFVQd9iOhJycnbCOaHR0Wug18BcX+5vn09rn1efaM92z4/fia+Wj5vfj194j4fvrH/S4CEAhnDkcUWBm+HIEdFByqGDwToQzPBVf/7vlz9UfyxvAu8DrwSfHF8rv0pfdO+8n/+wTaCroQrRXsGLEaihqYGJAV1xGaDfoJGAeGBXIFLQYEB7kH6QffBkwESwBH+2r1Bu+b6AzjPd4M2trWWdRs0/rSotMR1R3Zb95b5THuXvlhBXQQtxkoIVQmWSfbJB4gQBlzEYAJOAM4/rD6o/iX+PD45Pju+NT4C/ic9gr2YPYK+L36Lf8hBQoMHRJIF14bTB34HF0aoBaEEWcLOAXy/xn7h/bn8q3wau9N7hfupe/n8SH17Pk2ALIGdgwBEhEXeBqGGyIbKBkBFgQSQw4fC7IIKAfRBgYHBAeaBpEFiQNdAAv80/Zc8VfshefR4mve7trE2GnXjdb/1ZXWMtlJ3XziROnc8QH8hgbVD9sWCR3TID0hrB6bGuMUnA7tCOUDKAB8/fH7dPte+8X6Gfp++Xz4dveX9t72ovis+63/4QTvCsAQixW3GIQa9xr2GF4VxxCOC9sFqwBV/Of4H/bt87HyA/K38fbxffPD9aH48fy3AnkI1w2/EvEWjxluGrcZoxdbFIsQMg1HCvcHlQZOBl8GPQZ+BREElQHL/dH4efME7qfoeON43nHav9dq1n/V39V4157azN6d5FHrWvPt+14F+A2zFFcZehzEHRkciRgIFDMPXQrnBVgC4f9i/oz9If1z/DX7HPr4+Kn3nvbF9jv4t/ow/oACqQfXDJsRNBXOF6YYGRhEFkYT/A5hCpcFyQBB/Fz4F/XL8nXx//C68aDzVvbf+ez9kgJeB8wLTw8DEu8T4RTkFCUU6hI0EdIPkg43DRQM+wrLCWAIQgbBA54ABP3Q+Ev0x+9b6+3m1uKh37zcc9rV2E3YuNgz2izdvuEP5/bsHvRc/EsEOwt3EQ4W+xgHGlsZ3RaSE44PoQsgCNkEMwKLAI3/lP6S/Yv8kPtt+lH5N/im9x/4n/lM/ML/xQNgCBQNWxGcFLYWdRf0FtUUoxGJDf8IUQTh/7j7QfjK9Rr0bvOy8+b0tfaC+cr8DACgA0QH1AplDdQPphH7EoMTyBNTE4YSNRHrD1YOaQxQCnsIegYNBD0BKf6G+sH2ffLz7V3pQ+Xv4Ebdldrg2ALYa9hj2pndueGz5p7sLPP2+bkA4AYBDBwQChONFMYUBBRVEi8Qmw0eC64IYwZXBKMCNAGE//f9X/wf+7/51fhD+Jn4f/lE+6/9zgB6BGoIQgyaD4oSdBQqFWcU6hIlEHAM/AfLA6j/q/uD+E72FvWN9AH1UfYv+IT6av1LAPMC/gUMCQMMfQ6CEPoRABNXEw0TKxLOECsPOw07CzIJ/gbeBMwClgDo/cz6jPcn9HvwMext6PXkBOKC3x3ent1p3UneZ+C+413ncOse8HH17PrR/30ExwhgDMQOWBAiEY4QZA/vDSkM2Al5B3MFvwMqApcAYP9V/j/9Uvyg+yP7z/oG+9/7Sv07/68BngTMB+4K2A01EOsRsBKdEn8RkA+9DHkJ2wUYAo/+k/s0+Y73vvba9sj3TPky+7/9owBVAw8GpwjhCrIMSg6YDykQeBCCEFMQhQ9NDrEMPgsxCQkHuwSWAiMAs/07+6f4ifV78kzvQuzY6O/liOP64Z3gz98V4Ajh6eJs5R/pEe2J8Wr2vvvhAE4F8Aj7C0UObQ9pD8oOnA30CyMKMQg0BlwEpgIuAQMAyf6+/f78Vvzx+737w/tr/KT9Lf9JAd0D1Ab1CaAMCA/AELARtRHtEC8P5wwOChEHAgT8ABb+5fsm+sX4Mfhb+Cv5ofqX/An/pgF1BAsHgQlqCwwNOQ7iDjYP8Q5EDnANWwwOC7wJTAi3BvUEAQPUAIf+HPy6+UT3rfRB8hDwIO4I7PbpWOgM5wPmWOUj5bHl1eaP6OTqEe7s8SL2k/oP/x8DtQatCRoMgQ3YDVYNWAzjCuwI5wYOBWEDAQLnACcAgP/t/n/+Gf7A/WL9Nf1q/Rb+GP+QAKoCNAXOBxoKZgxCDnwP9Q/XD8QO6gyCCucHCgUrAqn/qP0j/CL7qvrn+sP7+fxt/mAAngLIBLcGrgiECuALvgxKDYwNRQ2uDLwLnwo9CbYHOQbOBCkDSAFj/3b9UPtJ+VH3UvVw87TxIfDo7ubt6Oz46zzrWuqO6THpLum66R3rWu3T7yTz+/Y1+1D/KwNDBuMIgQpbCzMLXgoYCc8HRwbJBFkDPQJZAcsAbAAuAMb/ef9J/xH/qv6E/sb+a/9KAKgBnQPLBQ0IXgpsDMwNwQ4ID4sOSQ12CycJsQYgBJwBTf+7/Z38D/wb/LH8tf0b/68AUAI4BBcG0weHCfEK7gtyDKEMvAxnDHILVwojCZkHtAXfAwgCHwAi/jr8avqe+J32CPXa88HycvEv8CTvEO7T7N3rKOs26sbpcuq761rtT+8i8ob1DPkm/Iz/uwJvBXkH6AjUCRoKzwksCVQI+AaOBWgEeQN2ApoB3wBgAP//mv8v/+j+uP6+/gn/oP+GANgBdANRBUQHLAnmChgM2Az4DJsMwgtiCpYIsQajBIMClwAD/7797/yZ/LH8d/2g/iYAFQINBDAGZAhECqcLxQxXDWsN9wzbC2QKnwi9BroEuQLBAPL+Mv2h+/75R/jQ9vT1JPUj9CPzWfKX8cjwu+/f7hzude3v7NHsXu3D7rnwF/P59fr4/fu8/pABmAMnBU0GTQeTB2sHBAd5Br8F7AQTBGkD8AKAAjYC9wGjAT4B2QBPANz/cf8t/0D/sP9AACcBgwITBL8FUAepCNgJvQoyCx0LjQqKCScIjAbQBAIDWgEuAEb/kP5t/uj+rv/NACgCvgM6BboGEQg1CcUJMQpNChwKYQmVCKYHjwYwBbwDDAJRAID+4vwv+375Efjs9tz1zvSg86fyjfFH8B/vMe5B7bvs2+yN7eDum/Cx8i710/d6+i/9qP+bAVcDxASsBQ0GHAbzBbsFTAXFBEoEzgNjAwsDpgI4AtgBmwFRAQ0B0ACVAHIAdwCMAMAARQEDAt0CyAO4BMIFogZQB7oHBQgLCMkHRgeFBpEFkwSIA64C+wFsARwBNAGUAR8C6QLUA84ElwVHBuIGdgfJB98HxweDB+0GMgZfBVUEFwO8AUQA1f5h/fH7sfrQ+RX5fPgt+Oz3f/fs9l72ivWP9HjzhvLJ8TLxAPF78VbyZfPP9Jv2n/i2+mP86v0q/08A7ACMAdAB8wERAmIClwLbAhsDggP9A0IERQRPBC8E3AM2A5EC8gFeAbIAQwAcACoAbAAWAdYBuAKoA7YEmQVYBsIGKAcqB/gGkwYeBosF5QQ1BKIDIQPUAqsCvALgAjsDnwMYBJoELAWPBdwFDAYZBvAFpQVNBdEEPwSXA+MCEgJDAWAAev+Q/rf97/xj/Nn7UPvT+lL6vPkw+Y745Pcs95L2C/ad9SX13/QC9Xb13vV79p/3n/h8+V36NPvS+078wvw7/Y/9sv0z/sn+Pv+4/4UAUwEHAqECRgOvA88DuQOoA14D9QKHAicC4QGfAYgBpgHnASsCqgJNA8sDMQSYBO0EGgU3BS4FFgXwBMEEjwRkBEgEOwRIBGQEjQSyBOgEBAUhBTAFHQX2BM4EiwQ9BOQDjgMsA9gChQI5AtkBYQHmAHQA+v9h/8X+X/4F/qn9dP1Y/Sr99PzB/Gr86vs8+4X60fn3+CL4jPcu9/n2Evdk9833S/ji+F/5u/nt+Sv6QfpV+oX62fob+3/7J/wa/f/92P7W/88AmwFRAtACIQNBAzIDCQO+AlwCBQLbAcABrgHVASQCdAK5AhADbgPEA/oDKQQ3BDYEJwQ4BDgEKAQkBEgEcgSVBLgE8gQUBUcFaQVxBV8FMQXlBJwEPATYA3wDMgPtAq8ChAJZAiIC7wG9AXoBGwGrAC4Aq/8p/6T+OP71/c39uf2e/X39Tv0P/cb8ePwm/L37WPv1+pv6Z/pI+h36+fn2+Qz6N/pR+lj6bfqa+uL6Cfs4+2n7qPvg+zb8fvzN/C39n/0d/pT+Dv90/8f/FwBjAJ0A3QANAUABawGUAagBsgG1AdMBAQIyAnMCvwIDA0MDfQOeA70DwwPAA8cDzgO/A6gDpAOzA7kDugO7A8gD2QPlA+8D4gPEA5oDWwMjA/sC1wK+Ap4CiAJrAlMCKQLyAbYBdAEyAfUAuAB1AEQAFADU/4j/P//9/sb+mv5w/k/+MP4R/ub9uf2A/UD9C/3j/MD8rPyl/JL8ifyS/Jj8j/yJ/Iv8hPx9/Hr8hfyP/Jr8q/y7/M786Pz0/A/9Of1j/Zb91/0o/nD+vf7+/k//mP/f/wwAJgA8AFIAXwB0AJIAwgD7AEUBlAHgASQCYAKgAtwC8AL9AvcC6gLNArkCrwKaApECmgKzAtEC9AIiA0wDawNxA2QDSgMTA9YCmwJmAi8CAwLcAbQBkQFuAVcBQAEnARAB8QDEAI8AVgAiAOr/p/9t/zv/Ev/i/sD+sf6o/qn+pf6Y/on+f/52/l/+R/4u/iD+DP7w/eT91f29/bL9vv3J/cr9zf3Z/dj91/3V/cv9zv3d/e39CP4z/l3+gf6i/s/+Af82/2X/fv+j/9D/5//t//j/CQANACAASABmAIkArwDGANgA6gDzAPYA+wD2AAwBMAFIAUgBOgE6AUsBVgFwAZQBqAGzAcABxgG/AbUBtgGsAZoBfwFiAT8BFQH0AOgA7wD8AAcBGAEiASkBKAEQAdwAqgCOAHEATAAzACoAHQARAA4ACAADAAEA///o/8r/oP92/0j/I/8D/+7+3P7M/tf+6/70/vz+/P7z/u3+6P7f/tj+1/7T/sf+xf7N/t3+5v7x/vr+CP8Z/yT/Lv8v/yb/F/8P/xX/J/8+/1L/Zf+L/63/yv/n//r/GAAxADMAPwBNAE0ASwBaAGoAdwCVALAAuwDKAN4A6QD7AAcBBgEBAfQA5wDdANEAyADUANwA8AAPASUBNAE8ATUBKQEbAQIB8ADbALoAnAB/AG8AcQB1AIIAkgCiAKkAowCLAGgAOAAJAOT/wv+e/4r/i/+M/5f/o/+z/77/yP/B/6//nv+E/3P/Y/9P/0P/PP80/zz/SP9X/17/YP9c/1f/Wf9f/2j/b/9n/2H/Y/9l/1//V/9T/1b/Xf9v/3z/iP+b/7T/wv/N/9v/4P/i/+f/9f/9//z/+/8CABAAHAAvADsARQBGAEcATgBTAFcAXgBpAHIAdQB3AG8AbABxAH0AhgCSAJsAngCmAK0ApwCcAIgAbgBTADwAJwAWABIAFgAfAC0APgBJAFMAXQBiAFUAOAAbAAUA9P/i/97/4f/o//v/DAAYACQAKQAtACsAGgAJAO3/zv+6/6//sv+4/7//zv/X/97/7P/x//T/9//5//f/5f/W/87/yP/D/73/uP+6/77/yf/Y/+D/5//s/+7/6P/g/9r/zP++/7n/uv/E/8v/2P/p//n/CwAWABgAFgASABEADQAFAAEAAQD//wEABQAIAAoADAAOAA4ADwAQAA4AEgASABMAFwAYABoAHgAiABsAFQATABMAFAAPABEAGwAiACwAMQA4ADgANAAuACYAGwAJAAIAAgD///3/AAADAAkAFAAcACIAHQAXABAA///y/+3/5v/f/+T/6v/y//j/+f///wAAAQAEAAgABwABAP//+f/1//f/9f/z//L/8f/t/+7/8P/u/+//8f/t/+z/7P/s/+//8//2//T/8//w/+v/6//r/+z/7f/w//T/9v/4//r/+P/3//n/+//6//v//f8AAAQABwAJAAsAEAAYABgAFwAWABYAFQATAA8AEAARAA0ADQAPAA8AEAAQABEAEgAOAA4ADwAPABEADgALAAgABwAHAAYABAAEAAsAEAAQABEAEgASABEAEgATABMAEwAOAA4ADgALAA0ADAAIAAcACAAFAAQABgAJAAgABgAFAAgACwALAAgACgAKAAcABQAEAAMAAwAAAAEABAADAAUACAAHAAcACQAMAA0ADwAPAAwACQAJAAgAAwAGAAgACwAMAAkABgAHAAoADAANAA8ADwAIAAcACwALAAUAAAD9//r/9//5//n/9f/3//j/9P/1//j/9f/3//j/9f/z//L//f8BAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
"""

def _require_env(name: str) -> str:
    value = os.getenv(name, "").strip()
    if not value:
        raise SystemExit(f"Missing required environment variable: {name}")
    return value


def _is_truthy_env(name: str) -> bool:
    return os.getenv(name, "").strip().casefold() in {"1", "true", "yes", "on"}


def _resolve_api_key() -> str:
    value = (
        os.getenv("SMOKE_INTERNAL_OPENAI_API_KEY", "").strip()
        or os.getenv("INTERNAL_OPENAI_API_KEY", "").strip()
    )
    if not value:
        raise SystemExit(
            "Missing required environment variable: SMOKE_INTERNAL_OPENAI_API_KEY"
        )
    return value


def _request_json(
    url: str, *, headers: dict[str, str] | None = None, body: dict | None = None
) -> tuple[int, dict]:
    data = None
    request_headers = dict(headers or {})
    if body is not None:
        data = json.dumps(body).encode()
        request_headers["Content-Type"] = "application/json"

    request = urllib.request.Request(url, headers=request_headers, data=data)
    try:
        with urllib.request.urlopen(request, timeout=30) as response:
            payload = response.read().decode()
            return response.status, json.loads(payload)
    except urllib.error.HTTPError as exc:
        payload = exc.read().decode()
        try:
            body_json = json.loads(payload)
        except json.JSONDecodeError:
            body_json = {"raw": payload}
        return exc.code, body_json


def _request_bytes(
    url: str,
    *,
    headers: dict[str, str] | None = None,
    body: dict | None = None,
) -> tuple[int, bytes, str]:
    data = None
    request_headers = dict(headers or {})
    if body is not None:
        data = json.dumps(body).encode()
        request_headers["Content-Type"] = "application/json"

    request = urllib.request.Request(url, headers=request_headers, data=data)
    try:
        with urllib.request.urlopen(request, timeout=30) as response:
            return (
                response.status,
                response.read(),
                response.headers.get("Content-Type", ""),
            )
    except urllib.error.HTTPError as exc:
        return exc.code, exc.read(), exc.headers.get("Content-Type", "")


def _request_multipart_bytes(
    url: str,
    *,
    headers: dict[str, str] | None = None,
    fields: dict[str, str] | None = None,
    file_field_name: str,
    file_name: str,
    file_content_type: str,
    file_bytes: bytes,
) -> tuple[int, bytes, str]:
    boundary = f"smoke-boundary-{int(time.time() * 1000)}"
    body = bytearray()
    for name, value in (fields or {}).items():
        body.extend(f"--{boundary}\r\n".encode())
        body.extend(
            f'Content-Disposition: form-data; name="{name}"\r\n\r\n{value}\r\n'.encode()
        )
    body.extend(f"--{boundary}\r\n".encode())
    body.extend(
        (
            f'Content-Disposition: form-data; name="{file_field_name}"; '
            f'filename="{file_name}"\r\n'
        ).encode()
    )
    body.extend(f"Content-Type: {file_content_type}\r\n\r\n".encode())
    body.extend(file_bytes)
    body.extend(b"\r\n")
    body.extend(f"--{boundary}--\r\n".encode())

    request_headers = dict(headers or {})
    request_headers["Content-Type"] = f"multipart/form-data; boundary={boundary}"
    request = urllib.request.Request(url, headers=request_headers, data=bytes(body))
    try:
        with urllib.request.urlopen(request, timeout=30) as response:
            return (
                response.status,
                response.read(),
                response.headers.get("Content-Type", ""),
            )
    except urllib.error.HTTPError as exc:
        return exc.code, exc.read(), exc.headers.get("Content-Type", "")


def _wait_for_success(
    *,
    request_fn,
    success_predicate,
    timeout_seconds: float,
    error_context: str,
) -> tuple[int, dict]:
    deadline = time.monotonic() + timeout_seconds
    last_result: tuple[int, dict] = (0, {"error": "not started"})

    while True:
        try:
            last_result = request_fn()
        except (urllib.error.URLError, OSError) as exc:
            last_result = (0, {"error": str(getattr(exc, "reason", exc))})

        status, payload = last_result
        if success_predicate(status, payload):
            return last_result
        if time.monotonic() >= deadline:
            raise SystemExit(f"{error_context}: {status} {payload}")
        time.sleep(2)


def main() -> int:
    base_url = os.getenv("SMOKE_BASE_URL", "http://127.0.0.1:18080").rstrip("/")
    api_key = _resolve_api_key()
    timeout_seconds = float(os.getenv("SMOKE_TIMEOUT_SECONDS", "120"))
    deadline = time.monotonic() + timeout_seconds

    while True:
        try:
            status, payload = _request_json(f"{base_url}/readyz")
        except (urllib.error.URLError, OSError) as exc:
            status, payload = 0, {"error": str(getattr(exc, "reason", exc))}
        if status == 200 and payload.get("status") == "ready":
            break
        if time.monotonic() >= deadline:
            raise SystemExit(
                f"/readyz did not become ready before timeout: {status} {payload}"
            )
        time.sleep(2)

    auth_headers = {"Authorization": f"Bearer {api_key}"}
    status, payload = _wait_for_success(
        request_fn=lambda: _request_json(f"{base_url}/v1/models", headers=auth_headers),
        success_predicate=lambda status, payload: status == 200,
        timeout_seconds=30.0,
        error_context="/v1/models did not stabilize before timeout",
    )

    model_ids = {
        entry.get("id") for entry in payload.get("data", []) if isinstance(entry, dict)
    }
    required_models = {"assistant-v1", "assistant-fast"}
    if not required_models.issubset(model_ids):
        raise SystemExit(
            f"Required public model IDs missing from model list: {sorted(model_ids)}"
        )

    status, payload = _wait_for_success(
        request_fn=lambda: _request_json(
            f"{base_url}/v1/chat/completions",
            headers=auth_headers,
            body={
                "model": "assistant-fast",
                "messages": [{"role": "user", "content": "Reply with ok."}],
            },
        ),
        success_predicate=lambda status, payload: status == 200,
        timeout_seconds=45.0,
        error_context="/v1/chat/completions did not stabilize before timeout",
    )

    choices = payload.get("choices")
    if not isinstance(choices, list) or not choices:
        raise SystemExit(f"Chat response missing choices: {payload}")

    message = choices[0].get("message") if isinstance(choices[0], dict) else None
    content = message.get("content", "").strip() if isinstance(message, dict) else ""
    if not content:
        raise SystemExit(f"Chat response content was empty: {payload}")

    if _is_truthy_env("SMOKE_CHECK_VOICE"):
        status, body, content_type = _request_bytes(
            f"{base_url}/v1/audio/speech",
            headers=auth_headers,
            body={
                "model": "tts-1",
                "input": "Скажи привет.",
                "voice": os.getenv("SMOKE_TTS_VOICE", "assistant-default"),
            },
        )
        if status != 200:
            try:
                payload = json.loads(body.decode())
            except Exception:
                payload = {"raw": body.decode(errors="ignore")}
            raise SystemExit(f"/v1/audio/speech failed: {status} {payload}")
        if not content_type.startswith("audio/wav"):
            raise SystemExit(
                f"/v1/audio/speech returned unexpected content type: {content_type}"
            )
        if len(body) < 16 or not body.startswith(b"RIFF"):
            raise SystemExit("/v1/audio/speech did not return RIFF/WAV audio")

    if _is_truthy_env("SMOKE_CHECK_STT"):
        stt_sample = base64.b64decode("".join(_SMOKE_STT_SAMPLE_WAV_B64.split()))
        status, body, content_type = _request_multipart_bytes(
            f"{base_url}/v1/audio/transcriptions",
            headers=auth_headers,
            fields={"model": "whisper-1"},
            file_field_name="file",
            file_name="smoke-hello.wav",
            file_content_type="audio/wav",
            file_bytes=stt_sample,
        )
        if status != 200:
            try:
                payload = json.loads(body.decode())
            except Exception:
                payload = {"raw": body.decode(errors="ignore")}
            raise SystemExit(f"/v1/audio/transcriptions failed: {status} {payload}")
        if not content_type.startswith("application/json"):
            raise SystemExit(
                "/v1/audio/transcriptions returned unexpected content type: "
                f"{content_type}"
            )
        try:
            payload = json.loads(body.decode())
        except json.JSONDecodeError as exc:
            raise SystemExit(
                "/v1/audio/transcriptions returned invalid JSON"
            ) from exc
        text = payload.get("text") if isinstance(payload, dict) else None
        if not isinstance(text, str):
            raise SystemExit(
                "/v1/audio/transcriptions returned unexpected payload: "
                f"{payload}"
            )
        normalized = " ".join(text.casefold().split())
        if "hello" not in normalized:
            raise SystemExit(
                "/v1/audio/transcriptions returned unexpected transcript: "
                f"{text!r}"
            )

    print("Smoke checks passed")
    return 0


if __name__ == "__main__":
    sys.exit(main())
